[build]
  # Run build from root to avoid confusion, explicitly entering frontend
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
